---
- name: "[default] Rust: check"
  stat:
    path: "/home/{{ ansible_user }}/.cargo/bin/rustc"
  register: rust_binary_dir

- name: "[default] Rust: Install rust"
  when: not rust_binary_dir.stat.exists
  become: false
  block:
    - name: "[default] download installation script"
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh
        mode: "0755"

    - name: "[default] install rust from script"
      command: /tmp/rustup.sh -y
      args:
        creates: /home/{{ ansible_user }}/.cargo/bin/rustc

    - name: "[default] remove installation script"
      file:
        path: /tmp/rustup.sh
        state: absent
