---
- name: "[default] GoLang: Install golang"
  block:
    - name: "[default] download"
      get_url:
        url: "https://dl.google.com/go/go{{ golang_version }}.{{ golang_aarch }}.tar.gz"
        dest: "{{ golang_path }}/go{{ golang_version }}.tar.gz"
        mode: "0644"
        validate_certs: no

    - name: "[default] extract"
      unarchive:
        src: "{{ golang_path }}/go{{ golang_version }}.tar.gz"
        dest: "{{ golang_path }}"
        remote_src: yes

    - name: "[default] prepare golang dir"
      command: "mv {{ golang_path }}/go {{ golang_path }}/go{{ golang_version }}"

    - name: "[default] remove sources"
      file:
        path: "{{ golang_path }}/go{{ golang_version }}.tar.gz"
        state: absent