---
- become: true
  block:
    - name: Set profile
      vars:
        go_env_vars:
          - "export GOPATH={{ user_path }}/go"
          - "export GOROOT={{ golang_source_path }}/go{{ golang_version }}"
          - "export GOBIN=${GOPATH}/bin"
      lineinfile:
        path: "{{ user_path + '/' + env_var_entry.1 if '/' not in env_var_entry.1 else env_var_entry.1 }}"
        regexp: "^{{ env_var_entry.0.split('=')[0] }}"
        line: "{{ env_var_entry.0 }}"
      loop: "{{ go_env_vars | product(profiles) | list }}"
      loop_control:
        loop_var: env_var_entry
    - name: Set PATH
      lineinfile:
        path: "{{ user_path + '/' + profile_path if '/' not in profile_path else profile_path }}"
        line: 'export PATH=$PATH:{{ golang_source_path }}/go{{ golang_version }}/bin:{{ user_path }}/go/bin'
        insertafter: EOF
        state: present
        regexp: '^export PATH=.*/go.*/bin$'
      loop: "{{ profiles }}"
      loop_control:
        loop_var: profile_path

  when:
    - ansible_os_family in ['Debian', 'RedHat', 'Darwin']
    - user_path is defined and user_path