---
- block:
  - name: Check OS
    fail:
      msg: "Unsupported platform: {{ ansible_os_family }}"
    when: ansible_os_family not in ['Debian']

  - name: Install GVM Debian-based Systems
    block:
      - name: Install bison
        become: true
        apt:
          name:
            - bison
            - git
            - curl
          state: present
      - name: Get installer
        ansible.builtin.get_url:
          url: https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer
          dest: /tmp/gvm-installer.sh
          mode: '0755'
      - name: Install GVM
        command:
          cmd: /bin/bash /tmp/gvm-installer.sh
        args:
          creates: "{{ ansible_env.HOME }}/.gvm/scripts/gvm"
    when: ansible_facts['os_family'] == "Debian"
