---
- become: true
  block:
  - name: Download sources
    get_url:
      url: "{{ golang_source_url }}"
      dest: "/tmp/go{{ golang_version }}.tar.gz"
      mode: '0755'
  - name: Check source path
    file:
      path: "{{ golang_source_path }}"
      state: directory
      mode: '0755'
      owner: root
      group: root
  - name: Extract sources
    unarchive:
      src: "/tmp/go{{ golang_version }}.tar.gz"
      dest: "{{ golang_source_path }}"
      remote_src: yes
  - name: Cleanup
    file:
      path: "{{ golang_source_path }}/go{{ golang_version }}"
      state: absent
  - name: Rename sources
    command:
      cmd: "mv {{ golang_source_path }}/go {{ golang_source_path }}/go{{ golang_version }}"
  - name: Cleanup
    file:
      path: "/tmp/go{{ golang_version }}.tar.gz"
      state: absent

  when:
    - ansible_os_family in ['Debian', 'RedHat', 'Darwin']
