---
- name: "[default] Devel pkg: checking git, Ubuntu"
  stat:
    path: /usr/bin/git
  register: git_binary

- name: "[default] Devel pkg: install git, Ubuntu"
  apt:
    name: git
    state: present

  when: ansible_pkg_mgr == 'apt' and git_binary.stat.exists == false
  changed_when: false

- name: "[default] Devel pkg: git, CentOS/RHEL"
  yum:
    name: git
    state: present

  when: ansible_pkg_mgr == 'yum' and git_binary.stat.exists == false
  changed_when: false