---
- name: "[default] Devel pkg: Configure PPAs, Ubuntu"
  when: ansible_pkg_mgr == 'apt'
  block:
    - name: "[default] ppa:deadsnakes"
      apt_repository:
        repo: "ppa:deadsnakes/ppa"
        state: present

    # add common repos here ...

    - name: "[default] update repo cache"
      apt:
        update_cache: yes

