---
- name: "Prepare environment for Raspberry PI - developer"
  hosts: PiDev

  roles:
    - { role: raspberry, when: raspberry == true }
    - { role: docker,    when: docker == true }
    - { role: golang,    when: golang == true }
    - { role: python,    when: python == true }
    - { role: nodejs,    when: nodejs == true }
    - { role: nvim,      when: nvim == true }
    - { role: zsh,       when: zsh == true }
