---
- name: "Prepare environment for Raspberry PI - developer"
  hosts: PiDev

  roles:
    - { role: upgrade,   when: upgrade == true }
    - { role: network,   when: network == true }
    - { role: zsh,       when: zsh == true }

    - { role: docker,    when: docker == true }
    - { role: golang,    when: golang == true }
    - { role: nodejs,    when: nodejs == true }
    - { role: python,    when: python == true }
    - { role: nvim,      when: nvim == true }
