---
- block:
  - name: Check OS
    fail:
      msg: "Unsupported platform: {{ ansible_os_family }}"
    when: ansible_os_family not in ['Debian', 'RedHat', 'Darwin']
  - name: Check Architecture
    fail:
      msg: "Unsupported architecture: {{ ansible_architecture }}"
    when: ansible_architecture not in nodejs_arch_map

   # Routing rules ...
  - name: Install from sources
    block:
      - name: Install
        include_tasks: "source.yml"
        when: ansible_os_family in ['Debian', 'RedHat', 'Darwin']
    when: nodejs_role__type == 'source'

  when:
    - nodejs_required
