---
- become: true
  block:
  - name: Download sources
    get_url:
      url: "{{ nodejs_source_url }}"
      dest: "/tmp/node{{ nodejs_version }}.tar.gz"
      mode: '0755'
  - name: Check source path
    file:
      path: "{{ nodejs_source_path }}"
      state: directory
      mode: '0755'
      owner: root
      group: root
  - name: Extract sources
    unarchive:
      src: "/tmp/node{{ nodejs_version }}.tar.gz"
      dest: "{{ nodejs_source_path }}"
      remote_src: yes
  - name: Cleanup
    file:
      path: "{{ nodejs_source_path }}/node{{ nodejs_version }}"
      state: absent
  - name: Rename sources
    command:
      cmd: "mv {{ nodejs_source_path }}/node-v{{ nodejs_version }}-{{ nodejs_os_type }}-{{ nodejs_arch_type }} {{ nodejs_source_path }}/node{{ nodejs_version }}"
  - name: Cleanup
    file:
      path: "/tmp/node{{ nodejs_version }}.tar.gz"
      state: absent
