---
- become: true
  block:
  - name: Download sources
    get_url:
      url: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tar.xz"
      dest: "/tmp/Python-{{ python_version }}.tar.xz"
      mode: '0755'
  - name: Extract sources
    unarchive:
      src: "/tmp/Python-{{ python_version }}.tar.xz"
      dest: "/tmp"
      remote_src: yes
  - name: Set CC env
    set_fact:
      ansible_env:
        CC: "ccache gcc"
  - name: Configure
    command:
      cmd: "./configure --prefix={{ python_source_path }}/python{{ python_version }} {{ python_build_options | join(' ') }}"
      chdir: "/tmp/Python-{{ python_version }}"
  - name: Compile
    command:
      cmd: "make -j{{ ansible_processor_cores }}"
      chdir: "/tmp/Python-{{ python_version }}"
  - name: Install
    command:
      cmd: "make altinstall"
      chdir: "/tmp/Python-{{ python_version }}"
  - name: Prepare pip
    file:
      src: "/usr/local/bin/pip{{ python_version | regex_replace('^([0-9]+\\.[0-9]+).*', '\\1') }}"
      dest: /usr/local/bin/pip3
      state: link
  - name: Cleanup
    file:
      path: "/tmp/Python-{{ python_version }}"
      state: absent
