---
- name: "[default] Python: check"
  ignore_errors: yes
  command: "which python{{ python_version }}"
  register: python_installed

- name: "[default] Python: Install python, Raspberry Pi"
  when: python_installed.rc != 0 and ansible_architecture == 'aarch64' and 'Debian' in ansible_distribution
  block:
    - name: "[default] install dependencies"
      apt:
        name: [ build-essential, libssl-dev, zlib1g-dev, libncurses5-dev, libncursesw5-dev, libreadline-dev, libsqlite3-dev, libgdbm-dev, libdb5.3-dev, libbz2-dev, libexpat1-dev, liblzma-dev, tk-dev, libffi-dev ]
        state: present

    - name: "[default] download sources"
      become: false
      get_url:
        url: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tar.xz"
        dest: "/tmp/Python-{{ python_version }}.tar.xz"

    - name: "[default] extract sources"
      become: false
      unarchive:
        src: "/tmp/Python-{{ python_version }}.tar.xz"
        dest: "/tmp"
        remote_src: yes
        creates: "/tmp/Python-{{ python_version }}"

    - name: "[default] configure"
      shell: |
        cd /tmp/Python-{{ python_version }}
        ./configure --prefix=/usr/local

    - name: "[default] build"
      become: true
      shell: |
        cd /tmp/Python-{{ python_version }}
        make
        make altinstall
      args:
        creates: "/usr/local/bin/python3.11"

- name: "[default] Python: Install python, Ubuntu"
  when: python_installed.rc != 0 and ansible_distribution == 'Ubuntu'
  block:
    - name: "[default] ppa:deadsnakes"
      apt_repository:
        repo: "ppa:deadsnakes/ppa"
        state: present

    - name: "[default] update repo cache"
      apt:
        update_cache: yes

    - name: "[default] install python {{ python_version }}"
      apt:
        name: "python{{ python_version }}"
        state: present

    - name: "[default] install venv"
      apt:
        name: "python{{ python_version }}-venv"
        state: present

- name: "[default] Python: Configure"
  when: python_installed.rc != 0
  block:
    - name: "[default] install pip"
      command: "python3.11 -m ensurepip --root /usr/local"
