---
- block:
  - name: Check OS
    fail:
      msg: "Unsupported platform: {{ ansible_os_family }}"
    when: ansible_os_family not in ['Debian', 'RedHat']

   # Routing rules ...
  - name: Build and install on local
    block:
      - include_tasks: build-setup-debian.yml
        when: ansible_os_family == "Debian"
      - include_tasks: build-setup-redhat.yml
        when: ansible_os_family == "RedHat"

      - name: Local build and install
        include_tasks: "build.yml"
    when: python_role__type == 'build'

  when:
  - python_required