---
- become: true
  block:
    - name: Change shell
      user:
        name: "{{ user_name }}"
        shell: /usr/bin/zsh
    - name: add .zshrc
      become_user: "{{ user_name }}"
      ansible.builtin.file:
        path: "{{ user_path }}/.zshrc"
        state: touch

  when:
   - ansible_os_family in ['Debian', 'RedHat', 'Darwin']
   - user_name is defined and user_name
   - user_path is defined and user_path
