---

- name: "[default] install"
  become: true
  block:
    - name: Install zsh
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - zsh
      when: ansible_pkg_mgr == 'apt'
    - name: Install
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - zsh
      when: ansible_pkg_mgr == 'yum'
    - name: Install oh-my-zsh
      become: false
      shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: ~/.oh-my-zsh
      environment:
        RUNZSH: "no"
        CHSH: "no"
#    - name: Create links
#      file:
#        src: "/home/{{ ansible_user }}/{{ item.src }}"
#        dest: "/root/{{ item.dest }}"
#        state: link
#      loop:
#        - { name: ".zshrc", src: ".zshrc", dest: ".zshrc" }
#        - { name: ".oh-my-zsh", src: ".oh-my-zsh", dest: ".oh-my-zsh" }
    - name: Make defaults
      shell: "chsh -s /usr/bin/zsh {{ item }}"
      loop:
        - "{{ ansible_user }}"
      environment:
        USER: "{{ item }}"
  when:
    - ansible_os_family == "Debian" or ansible_os_family == "RedHat"
