---

- name: "[default] install"
  become: true
  block:
    - name: Install zsh
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - zsh
      when: ansible_pkg_mgr == 'apt'
    - name: Install zsh
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - zsh
      when: ansible_pkg_mgr == 'yum'
    - name: Set user home
      set_fact:
        user_home: "{{ ansible_env.HOME }}"
    - name: Install oh-my-zsh
      become: false
      shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: "{{ user_home }}/.oh-my-zsh"
      environment:
        RUNZSH: "no"
        CHSH: "no"
    - name: Make defaults
      shell: "chsh -s /usr/bin/zsh {{ ansible_user }}"
    - name: Get /etc/profile
      slurp:
        src: "/etc/profile"
      register: profile_content
    - name: Check /etc/profile content
      set_fact:
        filtered_content: "{{ (profile_content['content'] | b64decode).splitlines() | select('match', '^(export|alias) ') | list }}"
    - name: Update .zshrc
      become: false
      blockinfile:
        path: "{{ user_home }}/.zshrc"
        block: |
          {% for line in filtered_content %}
          {{ line }}
          {% endfor %}
        marker: "# {mark} ANSIBLE MANAGED BLOCK - /etc/profile content"

  when:
    - ansible_os_family == "Debian" or ansible_os_family == "RedHat"
