---
- name: "[default] Checking zsh"
  stat:
    path: /bin/zsh
  register: zsh_bin

- name: "[default] Install zsh Ubuntu"
  apt:
    name: zsh
    state: present

  when: ansible_pkg_mgr == 'apt' and zsh_bin.stat.exists == false
  changed_when: false

- name: "[default] Install zsh CentOS/RHEL"
  yum:
    name: zsh
    state: present

  when: ansible_pkg_mgr == 'yum' and zsh_bin.stat.exists == false
  changed_when: false

- name: "[default] Configure Oh My Zsh"
  become: false
  shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh
  environment:
    CHSH: "no"
    RUNZSH: "no"

  when: |
    (ansible_pkg_mgr == 'apt' and zsh_bin.stat.exists == false)
    or
    (ansible_pkg_mgr == 'yum' and zsh_bin.stat.exists == false)

- name: "[default] Update .zshrc file"
  template:
    src: templates/zshrc__default.j2
    dest: "/home/{{ ansible_user }}/.zshrc"

- name: "[default] Create the symbolic link for .zshrc"
  file:
    src: "/home/{{ ansible_user }}/.zshrc"
    dest: /root/.zshrc
    state: link

- name: "[default] Create the symbolic link for .oh-my-zsh"
  file:
    src: "/home/{{ ansible_user }}/.oh-my-zsh"
    dest: /root/.oh-my-zsh
    state: link

- name: "[default] Make zsh as default shell for root"
  shell: chsh -s /usr/bin/zsh root
  environment:
    USER: "root"

  when: |
    (ansible_pkg_mgr == 'apt' and zsh_bin.stat.exists == false)
    or
    (ansible_pkg_mgr == 'yum' and zsh_bin.stat.exists == false)

- name: "[default] Make zsh as default shell for {{ ansible_user }}"
  shell: chsh -s /usr/bin/zsh {{ ansible_user }}
  environment:
    USER: "{{ ansible_user }}"

  when: |
    (ansible_pkg_mgr == 'apt' and zsh_bin.stat.exists == false)
    or
    (ansible_pkg_mgr == 'yum' and zsh_bin.stat.exists == false)
