---
- become: true
  block:
    - name: Zsh
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - zsh

  when: ansible_os_family not in ['Debian', 'RedHat']