---
- block:
  - name: Check OS
    fail:
      msg: "Unsupported platform: {{ ansible_os_family }}"
    when: ansible_os_family not in ['Debian', 'RedHat']

  - name: Install Zsh
    block:
      - include_tasks: "install-linux.yml"
        when: ansible_os_family in ['Debian', 'RedHat']

      - include_tasks: "configure-zsh.yaml"
        loop: "{{ zsh_users }}"
        loop_control:
          loop_var: user
        when: ansible_os_family in ['Debian', 'RedHat', 'Darwin']

  - include_tasks: oh-my-zsh.yml
    loop: "{{ zsh_users }}"
    loop_control:
      loop_var: user
    when: zsh_oh_my_zsh_plugin

  when:
  - zsh_required