---
- name: "[default] NodeJS: Install node, Ubuntu"
  when: ansible_pkg_mgr == 'apt'
  block:
    - name: "[default] repository key"
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
      register: key_result

    - name: "[default] verify GPG key"
      fail:
        msg: "Failed to add GPG key for Node.js repository"
      when: key_result.failed

    - name: "[default] ppa:nodesource"
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ node_js_version }} {{ ansible_distribution_release }} main"
        state: present
        filename: "nodesource_{{ node_js_version }}.list"

    - name: "[default] install"
      apt:
        name: nodejs
        state: present
