---
- name: "[default] git: Install git"
  block:
    - name: "[default] checking git"
      ignore_errors: yes
      command: "which git"
      register: git_installed

    - name: "[default] install, deb"
      apt:
        name: git
        state: present

      when: ansible_pkg_mgr == 'apt' and git_installed.rc != 0
      changed_when: false

    - name: "[default] install, CentOS/RHEL"
      yum:
        name: git
        state: present

      when: ansible_pkg_mgr == 'yum' and git_installed.rc != 0
      changed_when: false
