---
- name: "[default] Update package manager cache"
  apt:
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: "[default] Update package manager cache"
  yum:
    name: "*"
    state: latest
  when: ansible_pkg_mgr == 'yum'

- name: "[default] Upgrade packages"
  apt:
    upgrade: safe
    autoremove: yes
  when: ansible_pkg_mgr == 'apt'

- name: "[default] Upgrade packages"
  yum:
    name: "*"
    state: latest
  when: ansible_pkg_mgr == 'yum'
