---
- block:
  - include_tasks: setup-redhat.yml
    when: ansible_os_family == 'RedHat'

  - include_tasks: setup-debian.yml
    when: ansible_os_family == 'Debian'

  - name: Install
    become: true
    package:
      name: "{{ docker_packages }}"
      state: present
    notify: restart docker
    when: "ansible_version.full is version_compare('2.12', '<') or ansible_os_family not in ['RedHat', 'Debian']"

  - name: Install (downgrade)
    become: true
    package:
      name: "{{ docker_packages }}"
      state: present
      allow_downgrade: true
    notify: restart docker
    when: "ansible_version.full is version_compare('2.12', '>=') and ansible_os_family in ['RedHat', 'Debian']"

  - name: Check /etc/docker/ directory
    file:
      path: /etc/docker
      state: directory
      mode: 0755
    when: docker_daemon_options.keys() | length > 0

  - name: Configure daemon options
    become: true
    copy:
      content: "{{ docker_daemon_options | to_nice_json }}"
      dest: /etc/docker/daemon.json
      mode: 0644
    when: docker_daemon_options.keys() | length > 0
    notify: restart docker

  - name: Check Docker daemon
    service:
      name: docker
      state: started
      enabled: true

  - name: Check docker group
    getent:
      database: group
      key: docker
      split: ':'
    when: docker_users | length > 0

  - name: Check users in group
    set_fact:
      at_least_one_user_to_modify: true
    when:
      - docker_users | length > 0
      - item not in ansible_facts.getent_group["docker"][2]
    with_items: "{{ docker_users }}"

  - name: Add users to the docker group
    user:
      name: "{{ item }}"
      groups: docker
      append: true
    with_items: "{{ docker_users }}"
    when: at_least_one_user_to_modify is defined

  - include_tasks: docker-compose.yml
    when: docker_install_compose | bool