---
- name: "[raspbian.devel] repository"
  become: true
  block:
    - name: Update cache
      apt:
        update_cache: yes
    - name: Upgrade pkgs
      apt:
        upgrade: safe
        autoremove: yes
    - name: Install pkgs
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - gcc
        - make
        - snapd
        - libiw-dev
  when: ansible_pkg_mgr == 'apt'
