---

- name: "[default] install"
  become: true
  block:
    - name: Install apt deps
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - snapd
      when: ansible_pkg_mgr == 'apt'
    - name: Install yum deps
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - snapd
      when: ansible_pkg_mgr == 'yum'
    - name: Install pkg
      command: snap install --classic nvim
      register: _exec_result
    - name: Alias from vi
      lineinfile:
        path: /etc/profile
        line: 'alias vi=/snap/bin/nvim'
        regexp: '^alias vi='
        create: yes
      when:
        - _exec_result.rc == 0
    - name: Alias from vim
      lineinfile:
        path: /etc/profile
        line: 'alias vim=/snap/bin/nvim'
        regexp: '^alias vim='
        create: yes
      when:
        - _exec_result.rc == 0
  when:
    - ansible_os_family == "Debian" or ansible_os_family == "RedHat"
