---
- become: true
  block:
  - name: Check dependencies
    package:
      name:
        - gcc
        - snapd
        - python3-venv
      state: present
  - name: Set PATH
    lineinfile:
      path: "/root/.bashrc"
      line: 'export PATH=$PATH:/snap/bin'
      regexp: '^export PATH=.*/snap/bin'
      insertafter: EOF
      state: present
  - name: Upgrade dependencies
    community.general.snap:
      name: core
      state: present
  - name: Checking old versions
    community.general.snap:
      name: nvim
      state: absent
  - name: Install
    community.general.snap:
      name: nvim
      state: present
      classic: yes
      channel: "{{ nvim_version }}"
