---
- block:
  - name: Check OS
    fail:
      msg: "Unsupported platform: {{ ansible_os_family }}"
    when: ansible_os_family not in ['Debian']

  - name: Get passwd info for all users
    getent:
      database: passwd
  - name: Prepare user info
    set_fact:
      user_path: "{{ ansible_facts.getent_passwd[item][4] }}"
      user_name: "{{ item }}"
    loop: "{{ nvim_users }}"
    when: ansible_facts.getent_passwd[item] is defined
    register: user_facts

  - block:
    - include_tasks: install-debian.yml
    - include_tasks: nvim_env.yml
      loop: "{{ user_facts.results }}"
      vars:
        user_path: "{{ item.ansible_facts.user_path }}"
    when: ansible_os_family == 'Debian'

  - include_tasks: nvim-plugins.yml
    loop: "{{ user_facts.results }}"
    vars:
      user_path: "{{ item.ansible_facts.user_path }}"
      user_name: "{{ item.ansible_facts.user_name }}"
    when:
      - ansible_os_family in ['Debian']
      - nvim_plugins_repo != ""

  when: nvim_required
