---
- name: "[default] NeoVim: Install neovim"
  block:
    - name: "[default] checking neovim"
      ignore_errors: yes
      command: "which nvim"
      register: neovim_installed

    - name: "[default] install, Ubuntu"
      apt:
        name: neovim
        state: present

      when: ansible_pkg_mgr == 'apt' and neovim_installed.rc != 0
      changed_when: false

    - name: "[default] install, CentOS/RHEL"
      yum:
        name: neovim
        state: present

      when: ansible_pkg_mgr == 'yum' and neovim_installed.rc != 0
      changed_when: false
