---
- name: "[default] NeoVim"
  block:
    - name: "[default] install requirements"
      apt:
        name: snapd
        state: present

    - name: "[default] install nvim"
      command: snap install --classic nvim

- name: "[default] NvChad"
  block:
    - name: "[default] get sources"
      become: false
      git:
        repo: https://github.com/NvChad/NvChad
        dest: ~/.config/nvim
        version: HEAD
        depth: 1

    - name: "[default]"
      become: false
      command: rm -rf ~/.config/nvim/lua/custom

    - name: "[default] add custom plugins"
      become: false
      git:
        repo: https://github.com/mr-chelyshkin/.nvim
        dest: ~/.config/nvim/lua/custom
        version: HEAD
